"""
Django settings for offline_exam_system project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url

# =========================================
# Base paths & .env loading
# =========================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env at project root
dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=dotenv_path)

# =========================================
# Core security & debug settings
# =========================================

# SECURITY WARNING: keep the secret key used in production secret!
# - In development: falls back to the existing hardcoded key (no behavior change)
# - In production: set SECRET_KEY in environment / .env
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-83u_0ai5(qobklao2rdb(wj4-!9i0&j2-n$v=_y(gckysyejvf",
)

# SECURITY WARNING: don't run with debug turned on in production!
# - Default remains True (same as before) for local/dev
# - In production: set DJANGO_DEBUG=false
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

# Allowed hosts:
# - In dev (DEBUG=True): Django ignores ALLOWED_HOSTS, so default [] is fine.
# - In production (DEBUG=False): must set DJANGO_ALLOWED_HOSTS, e.g. "example.com,www.example.com"
_raw_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
if _raw_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _raw_allowed_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = []

# Optional: CSRF trusted origins for production (e.g. "https://example.com,https://www.example.com")
_raw_csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _raw_csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_trusted.split(",") if o.strip()]

# =========================================
# Application definition
# =========================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "offline_exam_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "offline_exam_system.wsgi.application"

# =========================================
# Database
# =========================================

# DATABASE_URL must be provided via .env (same behavior as before).
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError(f"DATABASE_URL not set. Check your .env file at {dotenv_path}")

DATABASES = {
    "default": dj_database_url.parse(DATABASE_URL)
}

# =========================================
# Password validation
# =========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =========================================
# Internationalization
# =========================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================================
# Static & media files
# =========================================

STATIC_URL = "static/"

# Location for collected static files in production (safe; not used in dev unless you run collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "core/static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =========================================
# Email Configuration
# =========================================
# For Gmail:
# 1. Enable 2FA on your Google account
# 2. Generate app password: https://myaccount.google.com/apppasswords
# 3. Add EMAIL_HOST_USER and EMAIL_HOST_PASSWORD to .env

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =========================================
# Logging Configuration
# =========================================
# Logs security events, warnings, and errors to file for audit trail.
# Prints in-flight debug messages do NOT appear in logs (prevents information leakage).

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} - {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'exam_system': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# =========================================
# Security hardening (only when DEBUG=False)
# =========================================

if not DEBUG:
    # Force HTTPS-related protections in production; all env-tunable
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
    ).lower() == "true"
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True").lower() == "true"

    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Frame/Clickjacking protection: prevent site from being embedded in iframes
    X_FRAME_OPTIONS = "DENY"

    # Content Security Policy: restrict resource loading to same-origin
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'", "'unsafe-inline'"),  # unsafe-inline needed for inline JS (examsetup.js, etc)
        "style-src": ("'self'", "'unsafe-inline'"),  # unsafe-inline for inline CSS
        "img-src": ("'self'", "data:"),  # allow data URIs for QR codes
        "font-src": ("'self'",),
        "connect-src": ("'self'",),
    }

# =========================================
# Misc
# =========================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password reset link configuration
PASSWORD_RESET_TIMEOUT_SECONDS = 3600  # 1 hour