# Generated by Django 6.0.1 on 2026-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'registration_number', 'student_id')},
        ),
        migrations.RemoveField(
            model_name='studentdatafile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentdatafile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentdatafile',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='default value', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
