# Generated by Django 5.2.10 on 2026-01-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seatallocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
