# Generated by Django 6.0.1 on 2026-02-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_attendance_sheet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_file', 'roll_number', 'registration_number', 'student_id')},
        ),
    ]
