# Generated by Django 5.2.10 on 2026-01-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_seatallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('seat_code', models.CharField(max_length=10)),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_session', models.CharField(default='First Half', max_length=50)),
                ('exam_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.room')),
            ],
            options={
                'unique_together': {('exam', 'room', 'registration_number')},
            },
        ),
    ]
