# Generated by Django 6.0.1 on 2026-03-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('create', 'Create Exam'), ('attendance', 'Attendance Sheet'), ('marks', 'Marks Sheet')], default='create', max_length=50),
        ),
        migrations.CreateModel(
            name='MarksSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_data', models.JSONField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_sheets', to='core.exam')),
                ('student_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_sheets', to='core.studentdatafile')),
            ],
        ),
    ]
