# Generated by Django 6.0.1 on 2026-03-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_exam_type_markssheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.DeleteModel(
            name='MarksSheet',
        ),
    ]
