# Generated by Django 5.2.10 on 2026-02-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminloginaudit_blockedadminemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLoginAudit',
        ),
    ]
