# Generated by Django 5.2.10 on 2026-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_adminloginaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentexam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentexam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
