# Generated by Django 6.0.1 on 2026-03-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_markssheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='rooms_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='schedule_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
