# Generated by Django 6.0.1 on 2026-03-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exam_rooms_file_name_exam_schedule_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='rooms_file_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='schedule_file_name',
        ),
        migrations.AddField(
            model_name='departmentexam',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
