# Generated by Django 5.2.10 on 2026-02-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seatallocation_end_time_seatallocation_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatallocation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='start_time',
        ),
    ]
