# Generated by Django 6.0.1 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_exam_rooms_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
