from django.urls import path
from .views import (
    admin_login,
    dashboard,
    exam_setup,
    attendance_wizard,
    init_temp_exam,
    update_temp_exam,
    generate_sheets,
    save_generated_sheets,
    get_generated_sheets,
    get_generated_sheet,
    delete_generated_sheet,
    complete_exam_setup,
    delete_temp_exam,
    delete_exam,
    delete_room,
    create_exam,
    upload_student_data,
    delete_student_file,
    get_file_students,
    update_students,
    add_file_students,
    add_departments,
    add_rooms,
    add_room_single,
    get_uploaded_files,
    save_selected_files,
    generate_seating,
    get_seating_data,
    lock_seating,
    get_exam_summary,
    student_portal,
    get_student_info,
    get_student_seat,
    get_all_exams,
    test_api,
    view_exam,
    generate_qr,
    qr_page,
    get_room_details,
    update_room_seating,
    add_student_to_seat,
    admin_logout,
    forgot_password,    
    reset_password,
    reset_password_link,
    upload_admin_emails,
    delete_admin_email,
    block_admin_email,
    get_generated_sheet,
    delete_generated_sheet,
    
)

urlpatterns = [
    path('', admin_login, name='admin_login'),
    path('dashboard/', dashboard, name='dashboard'),
    path('exam-setup/', exam_setup, name='exam_setup'),
    path('attendance-wizard/', attendance_wizard, name='attendance_wizard'),
    path('init-temp-exam/', init_temp_exam, name='init_temp_exam'),
    path('update-temp-exam/', update_temp_exam, name='update_temp_exam'),
    path('generate-sheets/', generate_sheets, name='generate_sheets'),
    path('save-generated-sheets/', save_generated_sheets, name='save_generated_sheets'),
    path('get-generated-sheets/', get_generated_sheets, name='get_generated_sheets'),
    path('get-generated-sheet/', get_generated_sheet, name='get_generated_sheet'),
    path('delete-generated-sheet/', delete_generated_sheet, name='delete_generated_sheet'),
    path('complete-exam-setup/', complete_exam_setup, name='complete_exam_setup'),
    path('delete-temp-exam/', delete_temp_exam, name='delete_temp_exam'),
    path('create_exam/', create_exam, name='create_exam'),
    path('upload-data/', upload_student_data, name='upload_data'),
    path('delete-file/<int:file_id>/', delete_student_file, name='delete_student_file'),
    path('get-file-students/', get_file_students, name='get_file_students'),
    path('update-students/', update_students, name='update_students'),
    path('add-file-students/', add_file_students, name='add_file_students'),
    path('add_departments/', add_departments, name='add_departments'),
    path('add_rooms/', add_rooms, name='add_rooms'),
    path('add_room/', add_room_single, name='add_room_single'),
    path('get_uploaded_files/', get_uploaded_files, name='get_uploaded_files'),
    path('save_selected_files/', save_selected_files, name='save_selected_files'),
    path('generate_seating/', generate_seating, name='generate_seating'),
    path('get_seating_data/<int:exam_id>/', get_seating_data, name='get_seating_data'),
    path('lock_seating/', lock_seating, name='lock_seating'),
    path('get_exam_summary/', get_exam_summary, name='get_exam_summary'),
    path('view-exam/<int:exam_id>/', view_exam, name='view_exam'),
    path('student-portal/', student_portal, name='student_portal'),
    path('get-student-info/', get_student_info, name='get_student_info'),
    path('get-student-seat/', get_student_seat, name='get_student_seat'),
    path('get-all-exams/', get_all_exams, name='get_all_exams'),
    path('delete-exam/', delete_exam, name='delete_exam'),
    path('delete_room/', delete_room, name='delete_room'),
    path('get_room_details/', get_room_details, name='get_room_details'),
    path('update_room_seating/', update_room_seating, name='update_room_seating'),
    path('add_student_to_seat/', add_student_to_seat, name='add_student_to_seat'),
    path('test-api/', test_api, name='test_api'),
    # QR endpoints
    path('generate_qr/', generate_qr, name='generate_qr'),
    path('qr/', qr_page, name='qr_page'),
    # Admin account management
    path('logout/', admin_logout, name='admin_logout'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('reset-password/', reset_password, name='reset_password'),
    path('reset-password-link/', reset_password_link, name='reset_password_link'),
    path('manage-admin-emails/', upload_admin_emails, name='manage_admin_emails'),
    path('delete-admin-email/<int:email_id>/', delete_admin_email, name='delete_admin_email'),
    path('block-admin-email/', block_admin_email, name='block_admin_email'),
]
